name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use a more recent version of checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      # --- THIS IS THE CORRECTED PART ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # Use the official AWS action
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # Set the region here

      # --- ADD THIS DEBUGGING STEP ---
      - name: Debug Environment Variables
        run: env | sort
      # --------------------------------
      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
